### ISSUE TITLE
escapeArgs goes terrible wrong

### ISSUE THREAD

**Issue by cojack** [danielgindi/node-vmrun#1]
Hi,
I have a problem with you escapeArgs method, there is no possibility to send escaped shell variable inside program parameter, fe:

```javascript
return VMRun.runProgramInGuest('/home/cojack/path/to/image.vmx',
  "C:\\windows\\system32\\WindowsPowerShell\\v1.0\\powershell.exe", [
    "\\$procs = \\$(Start-Process 'C:\\PathToProgramm' -PassThru -Verb runAs); \\$procs | Wait-Process"
  ], {
    interactive: true
  }).then(() => {
}).then(o => {
  console.log('works!');
}).catch(e => {
  console.error('some err', e);
});
``` 

it will be replaced to this:
```
'vmrun -T ws -gu perun -gp xxxxxx runProgramInGuest /home/cojack/path/to/image.vmx -interactive "C:\\\\windows\\\\system32\\\\WindowsPowerShell\\\\v1.0\\\\powershell.exe" "\\\\$procs = \\\\$(Start-Process \'C:\\\\PathToProgramm\' -PassThru -Verb runAs); \\\\$procs | Wait-Process"'
```
With error: 

```
/bin/sh: 1: Start-Process: not found

    at ChildProcess.exithandler (child_process.js:275:12)
    at emitTwo (events.js:126:13)
    at ChildProcess.emit (events.js:214:7)
    at maybeClose (internal/child_process.js:925:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:209:5)
```

Where it's wrong.

The only solution that I found is before require your module do:
```javascript
Object.defineProperty(process, 'platform', {
  value: 'win'
});
```

Could you improve your escaping for platform != win?

There is no need to replace `\\` with `\\\\`

Thanks in advance.

**Comment by danielgindi** [comment]
Well actually the `\` should be escaped, but only when not in a double quotes.
When inside the double quotes - only double quotes should be escaped, and with a backslash...
I'll fix it now, as I'm actually in front of the code

**Comment by danielgindi** [comment]
Wait, is it possible that you have passed an argument that is already quoted?

**Comment by danielgindi** [comment]
Should be OK now
